package com.hranalytics.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * Value object that carries user-supplied filter parameters through the analytics pipeline.
 * Owned and generated by the HR Analytics sub-system (read/write).
 */
public class FilterCriteria {

    private List<String> filterDepartment;   // empty = all departments
    private DateRange dateRange;
    private List<String> employeeCategory;   // e.g. "ACTIVE", "ON_LEAVE"
    private String filterStatus;             // "ALL", "ACTIVE", "INACTIVE"

    public FilterCriteria() {
        this.filterDepartment = new ArrayList<>();
        this.employeeCategory = new ArrayList<>();
        this.filterStatus = "ALL";
    }

    /** Resets all fields to their defaults, clearing any applied criteria. */
    public void reset() {
        filterDepartment.clear();
        employeeCategory.clear();
        filterStatus = "ALL";
        dateRange = null;
    }

    /** Returns true when the date range is present and valid. */
    public boolean hasValidDateRange() {
        return dateRange != null && dateRange.isValid();
    }

    public List<String> getFilterDepartment()           { return filterDepartment; }
    public void setFilterDepartment(List<String> deps)  { this.filterDepartment = deps; }

    public DateRange getDateRange()                     { return dateRange; }
    public void setDateRange(DateRange dateRange)       { this.dateRange = dateRange; }

    public List<String> getEmployeeCategory()               { return employeeCategory; }
    public void setEmployeeCategory(List<String> cats)      { this.employeeCategory = cats; }

    public String getFilterStatus()                     { return filterStatus; }
    public void setFilterStatus(String filterStatus)    { this.filterStatus = filterStatus; }

    @Override
    public String toString() {
        return String.format("FilterCriteria[depts=%s, status=%s, range=%s]",
                filterDepartment, filterStatus, dateRange);
    }
}
