package com.hrms.service;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * IHRAnalyticsReportingService — integration contract between the
 * Attrition-Risk subsystem and the HR Analytics & Reporting subsystem.
 *
 * The HR Analytics team will provide the concrete implementation of this
 * interface. This subsystem consumes it to push attrition-risk findings into
 * the organisation-wide HR dashboard and to pull aggregated workforce metrics
 * (turnover rates, headcount, engagement scores) that feed into risk scoring.
 *
 * SOLID: DIP — we depend on this abstraction, not on any concrete reporting class.
 */
public interface IHRAnalyticsReportingService {

    /**
     * Returns the current organisation-wide employee turnover rate as a
     * percentage (0-100), calculated over the trailing twelve months unless
     * the implementation specifies otherwise.
     *
     * @return Turnover rate percentage, e.g. 15.3 means 15.3%.
     */
    double getOrganisationTurnoverRate();

    /**
     * Returns a snapshot of the current headcount broken down by department.
     * Keys are department names; values are active headcount figures.
     *
     * @return Map of department -> active headcount.
     */
    Map<String, Integer> getHeadcountByDepartment();

    /**
     * Returns the average employee engagement score (0-100) for the given
     * department, sourced from the most recent engagement survey cycle.
     * Returns -1 if no survey data is available for that department.
     *
     * @param department Department name (must match the value stored in Employee).
     * @return Engagement score in [0, 100], or -1 if unavailable.
     */
    double getEngagementScore(String department);

    /**
     * Publishes an attrition-risk summary report generated by this subsystem
     * into the HR Analytics dashboard so it appears alongside other workforce
     * metrics. The report is identified by a unique reportId.
     *
     * @param report The risk summary report to push to the analytics dashboard.
     */
    void publishAttritionRiskReport(AttritionRiskReport report);

    /**
     * Fetches key HR metrics for a specific date range, aggregated at the
     * organisation level. Intended for feeding into correlation analyses.
     * Metric keys include (but are not limited to):
     * "avgTenureYears", "avgSatisfactionScore", "absenteeismRate".
     *
     * @param from Start of the reporting window (inclusive).
     * @param to   End of the reporting window (inclusive).
     * @return Map of metric name -> numeric value.
     */
    Map<String, Double> getAggregatedMetrics(LocalDate from, LocalDate to);

    // -----------------------------------------------------------------------
    // Nested DTO — the payload this subsystem sends to the analytics dashboard.
    // -----------------------------------------------------------------------

    /**
     * Represents a summarised attrition-risk report produced by the
     * Attrition-Risk subsystem for consumption by the HR Analytics dashboard.
     */
    interface AttritionRiskReport {
        /** Unique identifier for this report instance. */
        String getReportId();

        /** The date on which this report was generated. */
        LocalDate getGeneratedOn();

        /** Number of employees currently classified as HIGH attrition risk. */
        int getHighRiskCount();

        /** Number of employees currently classified as MEDIUM attrition risk. */
        int getMediumRiskCount();

        /** Number of employees currently classified as LOW attrition risk. */
        int getLowRiskCount();

        /**
         * Top root-cause labels driving attrition in this reporting cycle,
         * ordered by impact score descending (e.g. ["attendance", "tenure"]).
         */
        List<String> getTopRootCauses();

        /** A brief human-readable summary of the report findings. */
        String getSummary();
    }
}
